theme: jekyll-theme-cayman
title: ICMESH Project
description: 🌄🔒 Off-Grid, Secure Text Messaging for the Canyons of Orange County, CA 📡💬.  Use PRESET Medium-Slow to join the network.
github:
  is_project_page: false
